site_name: Painel de Gestão - Grupo Destak
nav:
  - Home: index.md
  - Financeiro:
    - Grupo Destak: financeiro/grupo_destak.md
    - Lançamentos Estoque: financeiro/lancamentos-estoque.md
  - Rebanho:
    - Arroba Produzido: rebanho/arroba_produzido.md
    - GMD Médio: rebanho/gmd_medio.md
  - Benchmark Cria : 
    - Custo por Cabeça: benchmark_cria/custo_por_cabeca.md
    - Faturamento Pecuário por HA:  benchmark_cria/faturamento_pecuario_por_ha.md
    - Faturamento por Funcionário:  benchmark_cria/faturamento_por_funcionario.md
    - GMD Global:  benchmark_cria/gmd_global.md
    - Lotação do Pasto:  benchmark_cria/lotacao_pasto.md
    - Mortalidade Animais Adultos:  benchmark_cria/mortalidade_animais_adultos.md
    - Mortalidade Bezerros:  benchmark_cria/mortalidade_bezerros.md
    - Precipitação Anual:  benchmark_cria/precipitacao-anual.md
  - Benchmark Recria : 
    - Custo por Cabeça: benchmark_recria/custo_por_cabeca.md
    - Faturamento Pecuário por HA:  benchmark_recria/faturamento_pecuario_por_ha.md
    - Faturamento por Funcionário:  benchmark_recria/faturamento_por_funcionario.md
    - GMD Global:  benchmark_recria/gmd_global.md
    - Lotação do Pasto:  benchmark_recria/lotacao_pasto.md
    - Mortalidade Animais Adultos:  benchmark_recria/mortalidade_animais_adultos.md
    - Precipitação Anual:  benchmark_recria/precipitacao-anual.md
  - Histórico de ajustes:  historico_de_ajustes.md

theme:
  name: material
  features:
    - announce.dismiss
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Mudar para tema claro
    - scheme: claro
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Mudar para tema escuto
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  language: pt

# Additional configuration
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

# Extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.tilde
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
